- name: Install docker
  gather_facts: No
  hosts: docker
  become: yes
  become_method: sudo

  tasks:
    - yum:
        name: epel-release
        state: latest
    - name: copy yum repo file
      copy:
        src: ./files/kubernetes.repo
        dest: /etc/yum.repos.d/kubernetes.repo
    - name: install kube packages
      yum:
        name: "{{ item }}"
        state: latest
      with_items:
        - "vim"
        - "kubectl"
        - "kubeadm"
        - "kubelet"
        - "python-pip"
    - name: copy selinux file
      copy:
        src: ./files/selinux
        dest: /etc/selinux/config
    - name: Reboot immediately if there was a change.
      shell: "sleep 5 && reboot"
      async: 1
      poll: 0

    - name: Wait for the reboot to complete if there was a change.
      wait_for_connection:
        connect_timeout: 20
        sleep: 5
        delay: 5
        timeout: 300
    - name: copy selinux file
      copy:
        src: ./files/k8s.conf
        dest: /etc/sysctl.d/k8s.conf
    - name: enable and start kubelet
      systemd:
        name: kubelet
        state: started
        enabled: yes

    - name: swap off
      command: swapoff -a

    - pip:
        name: pexpect

    - name: reset
      shell: yes 'y' | kubeadm reset

    - name: init kubeadm
      command: kubeadm init --pod-network-cidr=192.168.0.0/16 --apiserver-advertise-address=192.168.60.5

    - name: set cni
      shell: >
        sudo mkdir -p $HOME/.kube ;
        sudo cp /etc/kubernetes/admin.conf $HOME/.kube/config ;
        sudo chown $(id -u):$(id -g) $HOME/.kube/config ;
        sudo kubectl apply -f https://docs.projectcalico.org/v3.1/getting-started/kubernetes/installation/hosted/rbac-kdd.yaml ;
        sudo kubectl apply -f https://docs.projectcalico.org/v3.1/getting-started/kubernetes/installation/hosted/kubernetes-datastore/calico-networking/1.7/calico.yaml

    - name: create join file
      shell: sudo kubeadm token create --print-join-command > joinFile

    - name: copy join file to local
      fetch:
        src: ./joinFile
        dest: ./
